// Generated by CoffeeScript 1.5.0-pre
(function() {
  var iosocket;

  iosocket = io.connect();

  iosocket.on("connect", function() {
    $('#incomingChatMessages').append($('<li>Connected</li>'));
    iosocket.on("message", function(message) {
      return $('#incomingChatMessages').append($('<li></li>').text(message));
    });
    iosocket.on("disconnect", function() {
      return $('#incomingChatMessages').append('<li>Disconnected</li>');
    });
    return $('#outgoingChatMessage').keypress(function(event) {
      if (event.which === 13) {
        event.preventDefault();
        iosocket.send($('#outgoingChatMessage').val());
        $('#incomingChatMessages').append($('<li></li>').text($('#outgoingChatMessage').val()));
        return $('#outgoingChatMessage').val('');
      }
    });
  });

}).call(this);
